### ISSUE TITLE
Enable kernel features

### ISSUE THREAD

**Issue by FreddieOliveira** [LineageOS/android_device_xiaomi_lavender#6]
Hi. Where's the kernel source do you use? I'm asking this because I'd like to know if it's possible to enable some features that's not enabled by default, like Xbox controller support and some features necessary to [run docker](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27).

**Comment by bjo81** [comment]
It seems to be this one: https://github.com/LineageOS/android_kernel_xiaomi_sdm660
But why do you want to run docker on your phone?

**Comment by FreddieOliveira** [comment]
Yeah, I was checking its config and it seems to already have a lot of namespace and cgroups features enabled. I'll try to flash it to see if it's still missing something.

Running an Ubuntu container allows you to apt install pretty much anything. Your phone would then replace your computer for most of your tasks. Just imagine you finishing editing that vector drawing in Inkscape on your phone while waiting in supermarket's line. Also, you could experiment compiling, installing, messing with things and then simply delete the container without any side effects to your phone.

And besides, why not to run docker?
